import { readFileSync } from "node:fs";
import { join } from "node:path";
import { gunzipSync } from "node:zlib";

/**
 * The vendored Geocorr exports shipped in this package (ADR-008 §2; see `README.md` here):
 *
 * - `geocorr2022_sample.csv` — a hand-picked slice for the cousub↔CBSA and ZCTA↔tract pairs.
 * - `geocorr2022_place_county_natl.csv.gz` — the FULL national place→county crosswalk (#141),
 *   generated by `cli/fetch-geocorr.ts`. Census publishes no place↔county relationship file,
 *   so this is the only source of the edge the LAUS below-threshold fallback depends on.
 *
 * Both share the vendored schema `parseGeocorr` reads; this returns them as one CSV text.
 */
export function loadVendoredGeocorr(): string {
  const dir = import.meta.dirname;
  const sample = readFileSync(join(dir, "geocorr2022_sample.csv"), "utf-8").trimEnd();
  const national = gunzipSync(readFileSync(join(dir, "geocorr2022_place_county_natl.csv.gz")))
    .toString("utf-8")
    .trimEnd();
  const [, ...nationalRows] = national.split("\n"); // drop its header; the sample's serves
  return [sample, ...nationalRows].join("\n");
}
