#!/usr/bin/env bash
# Compile the OpenContext portal's runtime dependencies into a hash-pinned lock (#277).
#
# Fetches the commit pinned in opencontext.lock.json, keeps only the lines of its requirements.txt
# whose package is in the lock's `runtimeRequirements` allowlist (the version constraints stay
# upstream's), and compiles them with uv for the Lambda platform (Python 3.11, x86_64 manylinux)
# into opencontext.requirements.lock, stamped with the commit. Run it whenever the pinned commit or
# the allowlist changes, and commit the result:
#
#   scripts/lock-opencontext.sh
#
# scripts/bundle-opencontext.sh refuses a lock stamped with a different commit. Needs git, node, uv.
set -euo pipefail
cd "$(dirname "$0")/.."

LOCK_JSON="opencontext.lock.json"
OUT="opencontext.requirements.lock"
REPO="$(node -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).repository)' "$LOCK_JSON")"
COMMIT="$(node -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).commit)' "$LOCK_JSON")"
ALLOW="$(node -e 'console.log((JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).runtimeRequirements||[]).join("\n"))' "$LOCK_JSON")"
[[ "$COMMIT" =~ ^[0-9a-f]{40}$ ]] || { echo "::error:: $LOCK_JSON commit must be a full 40-hex SHA"; exit 1; }
[ -n "$ALLOW" ] || { echo "::error:: $LOCK_JSON has no runtimeRequirements"; exit 1; }
command -v uv >/dev/null 2>&1 || { echo "::error:: uv is required (https://docs.astral.sh/uv/)"; exit 1; }

WORK="build/opencontext-lock"
rm -rf "$WORK"
mkdir -p "$WORK/src"
git -C "$WORK/src" init -q
git -C "$WORK/src" fetch -q --depth 1 "$REPO" "$COMMIT"
git -C "$WORK/src" checkout -q FETCH_HEAD

# Keep the upstream line (with its constraint) for each allowlisted package; fail on a missing one.
node -e '
  const fs = require("fs");
  const norm = (s) => s.toLowerCase().replace(/[-_.]+/g, "-");
  const allow = process.argv[2].split("\n").filter(Boolean);
  const lines = fs.readFileSync(process.argv[1], "utf8").split("\n");
  const kept = [];
  for (const name of allow) {
    const line = lines.find((l) => { const m = /^\s*([A-Za-z0-9._-]+)/.exec(l); return m && norm(m[1]) === norm(name); });
    if (!line) { console.error(`::error:: ${name} is not in the pinned commit requirements.txt`); process.exit(1); }
    kept.push(line.trim());
  }
  fs.writeFileSync(process.argv[3], kept.join("\n") + "\n");
' "$WORK/src/requirements.txt" "$ALLOW" "$WORK/runtime.in"

uv pip compile "$WORK/runtime.in" --python-version 3.11 --python-platform x86_64-manylinux2014 \
  --generate-hashes --no-header --quiet -o "$WORK/compiled.txt"

{
  echo "# The OpenContext portal Lambda's runtime dependencies, hash-pinned (#277)."
  echo "# Generated by scripts/lock-opencontext.sh; do not edit. Regenerate when opencontext.lock.json changes."
  echo "# opencontext-commit: $COMMIT"
  echo "# platform: python 3.11, x86_64-manylinux2014"
  cat "$WORK/compiled.txt"
} > "$OUT"
echo "locked $(grep -cE '^[A-Za-z0-9]' "$OUT") packages for OpenContext $COMMIT -> $OUT"
